# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site
name: MilkAndTea
title: MilkAndTea's Blog
logo: https://avatars.githubusercontent.com/u/109011406?v=4
favicon: assets/images/logo.png
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
include: ["_pages"]
url: https://ghmilkandtea.github.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: / # the subpath of your site, e.g. /blog
twitter_username: biya1024
github_username:  GHMilkAndTea

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    avatar: 'assets/images/avatar-sal.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/donate/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Memoirs, a Bootstrap Medium styled template available for Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John
    avatar: 'assets/images/avatar.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."
  milkandtea:
    name: MilkAndTea
    display_name: Milkandtea
    avatar: https://avatars.githubusercontent.com/u/109011406?v=4
    email: k@luogu.org
    web: https://ghmilkandtea.github.io
    twitter: https://twitter.com/biya1024
    description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."


# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - rouge
  - kramdown
  - kramdown-math-katex
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - bootstrap
  - jekyll-gist
  - jekyll-optional-front-matter

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  math_engine: katex
  math_engine_opts: {}
  syntax_highlighter: rouge

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [README.md, Gemfile, Gemfile.lock]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
